# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_auto_20171130_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 1, 3, 11, 27524), max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='due',
            field=models.CharField(default=datetime.datetime(2017, 12, 1, 1, 3, 11, 27301), max_length=20),
        ),
    ]
