# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('deliver', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('by_when', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=200)),
                ('reward', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('requested_num', models.IntegerField(default=0)),
                ('fulfillment', models.IntegerField(default=0)),
                ('distance_traveled', models.FloatField(default=0)),
            ],
        ),
    ]
