# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 23, 47, 27, 845206), max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='due',
            field=models.CharField(default=datetime.datetime(2017, 11, 30, 23, 47, 27, 844980), max_length=20),
        ),
    ]
