# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0004_auto_20171201_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 2, 52, 59, 361794), max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='due',
            field=models.CharField(default=datetime.datetime(2017, 12, 1, 2, 52, 59, 361539), max_length=20),
        ),
    ]
