# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0007_auto_20171201_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='complete_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 3, 22, 26, 494187), max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 3, 22, 26, 494159), max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='due',
            field=models.CharField(default=datetime.datetime(2017, 12, 2, 3, 22, 26, 493913), max_length=20),
        ),
    ]
